chill:
  randomness: 0.885
  criteria:
    energy:
      multiplier: 2.0
      min: 0
      max: 1.0
    undergroundness:
      multiplier: 1.25
      min: 1
      max: 5
      slot_min_delta: -1.0
      slot_max_delta: 1.0
    valence:
      multiplier: 1
  slots:
    - criteria:
        energy: { target: 0.48, min: 0, max: 1}
        valence: { target: 0.65 }
    - criteria:
        energy: { target: 0.58, min: 0, max: 1}
        valence: { target: 0.78 }
    - criteria:
        energy: { target: 0.60, min: 0, max: 1}
        valence: { target: 0.6 }
    - criteria:
        energy: { target: 0.58, min: 0, max: 1}
        valence: { target: 0.58 }
    - criteria:
        energy: { target: 0.72, min: 0, max: 1}
        valence: { target: 0.72 }
    - criteria:
        energy:  { target: 0.62, min: 0, max: 1}
        valence: { target: 0.62 }
    - criteria:
        energy: { target: 0.36, min: 0, max: 1}
        valence: { target: 0.36 }
    - criteria:
        energy: { target: 0.60, min: 0, max: 1}
        valence: { target: 0.60 }
    - criteria:
        energy: { target: 0.70, min: 0, max: 1}
        valence: { target: 0.70 }
    - criteria:
        energy: { target: 0.68, min: 0, max: 1}
        valence: { target: 0.68 }
    - criteria:
        energy: { target: 0.68, min: 0, max: 1}
        valence: { target: 0.68 }
    - criteria:
        energy:  { target: 0.70, min: 0, max: 1}
        valence: { target: 0.70 }
    - criteria:
        energy: { target: 0.79, min: 0, max: 1}
        valence: { target: 0.79 }
    - criteria:
        energy: { target: 0.82, min: 0, max: 1}
        valence: { target: 0.82 }
    - criteria:
        energy: { target: 0.72, min: 0, max: 1}
        valence: { target: 0.72 }
    - criteria:
        energy: { target: 0.59,  min: 0, max: 1}
        valence: { target: 0.59 }
    - criteria:
        energy: { target: 0.72,  min: 0, max: 1}
        valence: { target: 0.72 }
    - criteria:
        energy: { target: 0.76, min: 0, max: 1}
        valence: { target: 0.76 }
    - criteria:
        energy: { target: 0.73, min: 0, max: 1}
        valence: { target: 0.73 }
    - criteria:
        energy: { target: 0.82, min: 0, max: 1}
        valence: { target: 0.82 }
    - criteria:
        energy: { target: 0.79, min: 0, max: 1}
        valence: { target: 0.79 }
    - criteria:
        energy: { target: 0.77, min: 0, max: 1}
        valence: { target: 0.77 }
    - criteria:
        energy: { target: 0.74, min: 0, max: 1}
        valence: { target: 0.74 }
    - criteria:
        energy: { target: 0.70, min: 0, max: 1}
        valence: { target: 0.70 }
    - criteria:
        energy:  { target: 0.78, min: 0, max: 1}
        valence: { target: 0.78 }
    - criteria:
        energy: { target: 0.81, min: 0, max: 1}
        valence: { target: 0.80 }
    - criteria:
        energy: { target: 0.83, min: 0, max: 1}
        valence: { target: 0.83 }
    - criteria:
        energy: { target: 0.79, min: 0, max: 1}
        valence: { target: 0.79 }
    - criteria:
        energy: { target: 0.84, min: 0, max: 1}
        valence: { target: 0.84 }
    - criteria:
        energy: { target: 0.70, min: 0, max: 1}
        valence: { target: 0.70 }
