lounge:
  randomness: 0.885
  criteria:
    energy:
      multiplier: 2.0
      min: 0
      max: 1.0
    undergroundness:
      multiplier: 1.25
      min: 1
      max: 5
      slot_min_delta: -1.0
      slot_max_delta: 1.0
    valence:
      multiplier: 0
  slots:
    - criteria:
        energy: { target: 0.68, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.66, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.70, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.73, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.78, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.77, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.62, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.73, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.83, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.75, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.74, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.79, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.89, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.83, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.76, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.59, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.73, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.79, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.76, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.85, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.81, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.77, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.74, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.70, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.78, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.81, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.83, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.79, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.90, min: .3, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.70, min: .3, max: 1 }
        valence: { target: 0.3 }
