mellow:
  randomness: 0.7
  criteria:
    energy:
      multiplier: 4.0
      min: 0
      max: 1.0
    undergroundness:
      multiplier: 1
      min: 1
      max: 5
      slot_min_delta: -1.0
      slot_max_delta: 1.0
    valence:
      multiplier: 2
  slots:
    - criteria:
        energy:  { target: 0.16, min: 0, max: .4 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.23, min: 0, max: .55 }
        valence: { target: 0.48 }
    - criteria:
        energy: { target: 0.30, min: 0, max: .54 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.44, min: 0, max: .64 }
        valence: { target: 0.52 }
    - criteria:
        energy: { target: 0.48, min: 0, max: .71 }
        valence: { target: 0.46 }
    - criteria:
        energy: { target: 0.32, min: 0, max: .78 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.36, min: 0, max: .9 }
        valence: { target: 0.36 }
    - criteria:
        energy: { target: 0.51, min: 0, max: .80 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.44, min: 0, max: .9 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.51, min: 0, max: .9 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.49, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.42, min: 0, max: .9 }
        valence: { target: 0.39 }
    - criteria:
        energy: { target: 0.49, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.52, min: 0, max: .9 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.45, min: 0, max: .9 }
        valence: { target: 0.5 }
    - criteria:
        energy: { target: 0.39, min: 0, max: .9 }
        valence: { target: 0.42 }
    - criteria:
        energy: { target: 0.28, min: 0, max: .9 }
        valence: { target: 0.6 }
    - criteria:
        energy: { target: 0.51, min: 0, max: .9 }
        valence: { target: 0.55 }
    - criteria:
        energy: { target: 0.44, min: 0, max: .9 }
        valence: { target: 0.6 }
    - criteria:
        energy: { target: 0.36, min: 0, max: .9 }
        valence: { target: 0.75 }
    - criteria:
        energy: { target: 0.25, min: 0, max: .9 }
        valence: { target: 0.1 }
    - criteria:
        energy: { target: 0.32, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.50, min: 0, max: .9 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.45, min: 0, max: .9 }
        valence: { target: 0.46 }
    - criteria:
        energy: { target: 0.48, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.46, min: 0, max: .9 }
        valence: { target: 0.2 }
    - criteria:
        energy: { target: 0.48, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.41, min: 0, max: .9 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.21, min: 0, max: .9 }
        valence: { target: 0.2 }
    - criteria:
        energy: { target: 0.36, min: 0, max: .9 }
        valence: { target: 0.4 }
