vibes:
  randomness: 0.7
  criteria:
    energy:
      multiplier: 4.0
      min: 0
      max: 1.0
    undergroundness:
      multiplier: 1
      min: 1
      max: 5
      slot_min_delta: -2.0
      slot_max_delta: 1.0
    valence:
      multiplier: 2
  slots:
    - criteria:
        energy: { target: 0.33, min: .2, max: .87 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.26, min: .2, max: .87 }
        valence: { target: 0.4 }
    - criteria:
        energy: { target: 0.22, min: .2, max: .87 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.31, min: .2, max: .87 }
        valence: { target: 0.24 }
    - criteria:
        energy: { target: 0.18, min: .2, max: .87 }
        valence: { target: 0.51 }
    - criteria:
        energy: { target: 0.42, min: .2, max: .87 }
        valence: { target: 0.32 }
    - criteria:
        energy: { target: 0.46, min: .2, max: .87 }
        valence: { target: 0.2 }
    - criteria:
        energy: { target: 0.52, min: .2, max: .87 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.38, min: .2, max: .87 }
        valence: { target: 0.05 }
    - criteria:
        energy: { target: 0.33, min: .2, max: .87 }
        valence: { target: 0.6 }
    - criteria:
        energy: { target: 0.25, min: .2, max: .87 }
        valence: { target: 0.29 }
    - criteria:
        energy: { target: 0.33, min: .2, max: .87 }
        valence: { target: 0.42 }
    - criteria:
        energy: { target: 0.40, min: .2, max: .87 }
        valence: { target: 0.8 }
    - criteria:
        energy: { target: 0.56, min: .2, max: .87 }
        valence: { target: 0.36 }
    - criteria:
        energy: { target: 0.60, min: .2, max: .87 }
        valence: { target: 0.42 }
    - criteria:
        energy: { target: 0.64, min: .2, max: .87 }
        valence: { target: 0.6 }
    - criteria:
        energy: { target: 0.33, min: .2, max: .87 }
        valence: { target: 0.56 }
    - criteria:
        energy: { target: 0.42, min: .2, max: .87 }
        valence: { target: 0.32 }
    - criteria:
        energy: { target: 0.44, min: .2, max: .87 }
        valence: { target: 0.36 }
    - criteria:
        energy: { target: 0.46, min: .2, max: .87 }
        valence: { target: 0.31 }
    - criteria:
        energy: { target: 0.56, min: .2, max: .87 }
        valence: { target: 0.43 }
    - criteria:
        energy: { target: 0.23, min: .2, max: .87 }
        valence: { target: 0.35 }
    - criteria:
        energy: { target: 0.57, min: .2, max: .87 }
        valence: { target: 0.5 }
    - criteria:
        energy: { target: 0.60, min: .2, max: .87 }
        valence: { target: 0.7 }
    - criteria:
        energy: { target: 0.54, min: .2, max: .87 }
        valence: { target: 0.20 }
    - criteria:
        energy: { target: 0.42, min: .2, max: .87 }
        valence: { target: 0.5 }
    - criteria:
        energy: { target: 0.40, min: .2, max: .87 }
        valence: { target: 0.53 }
    - criteria:
        energy: { target: 0.32, min: .2, max: .87 }
        valence: { target: 0.43 }
    - criteria:
        energy: { target: 0.53, min: .2, max: .87 }
        valence: { target: 0.10 }
    - criteria:
        energy: { target: 0.41, min: .2, max: .87 }
        valence: { target: 0.5 }
