mellow:
  randomness: 0.8
  criteria:
    energy:
      multiplier: 4.0
      min: 0
      max: 1.0
    undergroundness:
      multiplier: 1.0
      min: 1
      max: 5
      track_min_delta: -1.0
      track_max_delta: 1.0
    valence:
      multiplier: 1.0
  slots:
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
    - criteria:
        energy: { target: 0.3, min: 0, max: 1 }
        valence: { target: 0.3 }
